# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160530_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='amount',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='campaign',
            name='progress',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='publishercampaign',
            name='amount',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='publishercampaign',
            name='progress',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
